language: node_js
node_js:
  - 12

services:
  - docker
  
before_script: []

script:
  - docker --version
  - docker build -f udagram-api-feed/Dockerfile -t  ayanf3d3v/udagram-api-feed:v1 udagram-api-feed
  - docker build -f udagram-api-user/Dockerfile -t  ayanf3d3v/udagram-api-user:v1 udagram-api-user
  - docker build -f udagram-frontend/Dockerfile -t  ayanf3d3v/udagram-frontend:v1 udagram-frontend
  - docker build -f udagram-reverseproxy/Dockerfile -t  ayanf3d3v/udagram-reverseproxy:v1 udagram-reverseproxy


after_success:
  - echo "$dockerhub-pass" | docker login -u "$dockerhub-username" --password-stdin
  - docker push ayanf3d3v/udagram-api-feed:v1
  - docker push ayanf3d3v/udagram-api-user:v1
  - docker push ayanf3d3v/udagram-frontend:v1
  - docker push ayanf3d3v/udagram-reverseproxy:v1