version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v1.1
  api-user:
    build:
      context: ./udagram-api-user
    image: api-user:v1.0
  api-feed:
    build:
      context: ./udagram-api-feed
    image: api-feed:v1.0
  frontend:
    build:
      context: ./udagram-frontend
    image: frontend:v1.0
